### ISSUE TITLE
能否实现鼠标点击变成I形状后切换输入状态为中文

### ISSUE THREAD

**Issue by seszu** [flyinclouds/KBLAutoSwitch#10]
在很多软件中，如PS和CAD这些软件，很多功能快捷键是单字母形式的，比如单独按D、L、C、R这些键代表不同的快捷功能，而在这些软件中又频繁需要输入文字。。。。。
那么有没有一种方法，在鼠标变成I形状的时候（也就是出现提示状态图标的时候），输入状态变为中文输入，而鼠标指针变成普通形状的时候，输入状态变成纯英文模式

**Comment by flyinclouds** [comment]
相关功能考虑中
