### ISSUE TITLE
gvim热字串不能正确切换输入法

### ISSUE THREAD

**Issue by zichenw** [flyinclouds/KBLAutoSwitch#12]
高级窗口编辑器换切输入法在vscode和notepad都正常,在GVIM`; ` `# ` 这些热字串都没反应
```ini
[自定义窗口组]
1=全局窗口=0=AllGlobalWin=全局窗口组
2=编辑器=2=sublime_text.exe|Code.exe|gvim.exe|Notepad.exe|nvim.exe=编辑器窗口组
3=不重置大小写组=1=RunAny_SearchBar ahk_exe RunAny.exe=切换窗口不重置大小写
4=TC=2=ahk_exe TOTALCMD.exe|TotalCMD64.exe=TC
[自定义操作]
1=2=s-; |# |// =1=ahk、py注释切换中文
2=2=k-~Enter|~Esc|~CapsLock=6=回车、Esc切换英文
3=4=k-~F2|~F7|~^s=1=TC切换中文
4=4=k-~Enter|~Esc=6=TC回车或ESC重置输入法
```

**Comment by flyinclouds** [comment]
测试没有问题，没有复现出来

**Comment by flyinclouds** [comment]
> 高级窗口编辑器换切输入法在vscode和notepad都正常,在GVIM`; ` `# ` 这些热字串都没反应
> 
> ```ini
> [自定义窗口组]
> 1=全局窗口=0=AllGlobalWin=全局窗口组
> 2=编辑器=2=sublime_text.exe|Code.exe|gvim.exe|Notepad.exe|nvim.exe=编辑器窗口组
> 3=不重置大小写组=1=RunAny_SearchBar ahk_exe RunAny.exe=切换窗口不重置大小写
> 4=TC=2=ahk_exe TOTALCMD.exe|TotalCMD64.exe=TC
> [自定义操作]
> 1=2=s-; |# |// =1=ahk、py注释切换中文
> 2=2=k-~Enter|~Esc|~CapsLock=6=回车、Esc切换英文
> 3=4=k-~F2|~F7|~^s=1=TC切换中文
> 4=4=k-~Enter|~Esc=6=TC回车或ESC重置输入法
> ```

可以尝试更新版本，或加群进一步阐述问题

**Comment by zichenw** [comment]
> > 高级窗口编辑器换切输入法在vscode和notepad都正常,在GVIM`; ` `# ` 这些热字串都没反应
> > ```ini
> > [自定义窗口组]
> > 1=全局窗口=0=AllGlobalWin=全局窗口组
> > 2=编辑器=2=sublime_text.exe|Code.exe|gvim.exe|Notepad.exe|nvim.exe=编辑器窗口组
> > 3=不重置大小写组=1=RunAny_SearchBar ahk_exe RunAny.exe=切换窗口不重置大小写
> > 4=TC=2=ahk_exe TOTALCMD.exe|TotalCMD64.exe=TC
> > [自定义操作]
> > 1=2=s-; |# |// =1=ahk、py注释切换中文
> > 2=2=k-~Enter|~Esc|~CapsLock=6=回车、Esc切换英文
> > 3=4=k-~F2|~F7|~^s=1=TC切换中文
> > 4=4=k-~Enter|~Esc=6=TC回车或ESC重置输入法
> > ```
> 
> 可以尝试更新版本，或加群进一步阐述问题

[v2.3.3](https://github.com/flyinclouds/KBLAutoSwitch/releases/tag/v2.3.3)
新版已经可以正常使用了
