### ISSUE TITLE
切换中英文输入法不生效

### ISSUE THREAD

**Issue by onsalo** [flyinclouds/KBLAutoSwitch#2]
切换中英文输入法意思应该是在输入法之间切换吧，但似乎并不生效，只是在切换输入法的中英文状态

**Comment by flyinclouds** [comment]
是支持切换中英文输入法的，需要安装英文输入法，并在中英窗口-英文窗口中添加切换的窗口

**Comment by onsalo** [comment]
昨天下载的版本不可以切换，今天下载的最新版本就可以了,感谢
