### ISSUE TITLE
Tooltip显示输入法状态在多显示器的情况下edge中还存在显示到显示器最右侧的问题

### ISSUE THREAD

**Issue by yisqiu** [flyinclouds/KBLAutoSwitch#3]
2.1.6，win10x64 ，捕捉光标位置不正确

**Comment by flyinclouds** [comment]
是在高级配置-切换提示位置中设置的1（优先输入位置）吗？目前获取输入位置还不完善，建议目前设置为0或者使用鼠标指针来显示输入法状态

**Comment by yisqiu** [comment]
> 是在高级配置-切换提示位置中设置的1（优先输入位置）吗？目前获取输入位置还不完善，建议目前设置为0或者使用鼠标指针来显示输入法状态

是的

**Comment by yisqiu** [comment]
类似软件https://github.com/aardio/ImTip就准确得多，可以参考一下实现原理

**Comment by flyinclouds** [comment]
了解，主要是坐标体系问题，下个版本修复改善

**Comment by yisqiu** [comment]
> 了解，主要是坐标体系问题，下个版本修复改善

谢谢，还有最好能在设置面板中提供自定义tooltip位置的选项（偏移水平、垂直系数）！

**Comment by flyinclouds** [comment]
这个可能要下下个版本

**Comment by yisqiu** [comment]
> 这个可能要下下个版本

谢谢

**Comment by flyinclouds** [comment]
新版本会在交流群里面先发
