### ISSUE TITLE
在wps里使用shift切换中英文输入法存在问题

### ISSUE THREAD

**Issue by onsalo** [flyinclouds/KBLAutoSwitch#4]
切换到wps后，只有第一次按下shift才可以切换输入法，输入法状态显示正确，此后再按shift，输入法都不会改变，状态显示也是错的

**Comment by flyinclouds** [comment]
wps2019专业版，测试没有问题

**Comment by onsalo** [comment]
我用的是wps office，
当前版本
11.1.0.9914-release
检测更新
渠道号
20.2766
系统版本
Microsoft Windows 10 家庭中文版(64 位) Build 19042 v10.0.19042
![动画](https://user-images.githubusercontent.com/62136913/173987519-e91759b1-cdee-4e17-a4fa-2e98710159b8.gif)

**Comment by flyinclouds** [comment]
又测试了下，还是没有复现问题，是仅wps吗？

**Comment by flyinclouds** [comment]
![11](https://user-images.githubusercontent.com/55119048/173990933-b6628944-dee8-4013-892d-7996697f0446.gif)

**Comment by onsalo** [comment]
是的，仅wps，等我晚上回去再用其他电脑测一下

**Comment by onsalo** [comment]
我的电脑也是这种情况

**Comment by flyinclouds** [comment]
是否是以管理员运行的软件？

**Comment by onsalo** [comment]
是管理员

**Comment by onsalo** [comment]
[基本设置]
开机自启=1
管理员启动=1
自动切换=1
默认输入法=3
切换模式=1
Gui切换提示=1
Gui切换提示时间=1500
Gui切换提示文字大小=32
Gui切换提示透明度=150
Gui切换提示水平位置=45
Gui切换提示垂直位置=25
ToolTip切换提示=1
ToolTip切换提示时间=1500
ToolTip切换提示文字大小=11
ToolTip切换提示透明度=235
ToolTip切换提示水平偏移=-68
ToolTip切换提示垂直偏移=-32
切换提示位置=1
图标显示输入法=1
双击托盘图标=2
鼠标指针显示输入法=0
鼠标指针格式=0
鼠标指针对应分辨率=0
热键屏蔽程序列表=deadcells.exe
切换屏蔽程序列表=
[热键设置]
添加至中文窗口=+F5
添加至英文(中文)窗口=
添加至英文输入法窗口=
移除从中英文窗口=
切换中文=
切换英文(中文)=
切换英文输入法=
切换中英文(中文)=
切换中英文输入法=
显示当前输入法=
重置当前输入法=
停止自动切换=
获取输入法IME代码=
[特殊热键]
左Shift=5
右Shift=5
左Ctrl=0
右Ctrl=0
左Alt=0
右Alt=0
[高级设置]
内部关联=..\RunAny\RunAnyConfig.ini
快捷键兼容=1
左键点击输入位置显示输入法状态=1|全局窗口
定时重置输入法=60|编辑器
切换重置大小写=1
[自定义窗口组]
1=全局窗口=0=AllGlobalWin=全局窗口组
[自定义操作]
1==s-; |# =1=ahk、py注释切换中文
2==k-~Enter|~Esc=6=回车、Esc切换英文
[中文窗口]
[英文窗口]
[英文输入法窗口]
[焦点控件切换窗口]
Xshell=ahk_exe Xshell.exe
Steam=ahk_exe Steam.exe

**Comment by flyinclouds** [comment]
测试还是未能复现问题，暂时无法修复
如果有需要，可以首页加QQ交流群，有空的时候远程尝试解决

**Comment by better319** [comment]
解决 了吗？我是在excel里面正常的，wps里面不能中文。

**Comment by better319** [comment]
我好像解决了，在中英文窗口中如果是通过+号添加的会出现问题。通过热键配置→添加至中文窗口→(shift+\)。通过这个快捷键添加的话，好像就成功了 。不知道什么原因

**Comment by better319** [comment]
![image](https://github.com/flyinclouds/KBLAutoSwitch/assets/13842581/46f06724-2cce-427a-afab-ee444a8e3219)

**Comment by better319** [comment]
![image](https://github.com/flyinclouds/KBLAutoSwitch/assets/13842581/a70c1c14-ecf8-4b4c-b00f-ec7028e1e65a)
