### ISSUE TITLE
提示的背景色和前景色能否自定义

### ISSUE THREAD

**Issue by MaxSherry** [flyinclouds/KBLAutoSwitch#6]
提示的背景色和前景色能否自定义, 有时候提示背景色和输入框的背景色差不多一个色系, 导致提示信息看不清楚

**Comment by flyinclouds** [comment]
> 提示的背景色和前景色能否自定义, 有时候提示背景色和输入框的背景色差不多一个色系, 导致提示信息看不清楚

v2.2.2版本支持了，入口：高级配置-提示颜色

**Comment by MaxSherry** [comment]
中英文的背景色能否再区分一下.
现在是高级设置里有三个颜色设置, 能否再加一个背景色, 用来区分中文背景色, 英文背景, 谢谢

**Comment by flyinclouds** [comment]
> 中英文的背景色能否再区分一下. 现在是高级设置里有三个颜色设置, 能否再加一个背景色, 用来区分中文背景色, 英文背景, 谢谢

好的，下个版本是由这个计划的

**Comment by MaxSherry** [comment]
太给力了, 十分感谢

**Comment by MaxSherry** [comment]
你好,我个人还有一个想法, 就是tooltip显示的时候, 一般情况下后边的大小写"a"标识用不到,  正常输入的情况下, 如果中文输入, tooltip就显示"中", 如果英文输入,tooltip就显示"英", 如果切大写状态, tooltip就显示"A", 这样都简短一些. 谢谢
