### ISSUE TITLE
vscode下使用vim插件的情况下, 我在行尾点击一下鼠标左键,行尾总是被选中

### ISSUE THREAD

**Issue by MaxSherry** [flyinclouds/KBLAutoSwitch#7]
vscode下使用vim插件的情况下, 我在行尾点击一下鼠标左键,行尾总是被选中. 本来是vim正常的模式, 在行尾点击鼠标之后,就选中了行尾,导致变成vim的视图模式了.

**Comment by flyinclouds** [comment]
更新新版本2.1.9，应该能够减少这类问题

**Comment by MaxSherry** [comment]
十分感谢, 我更新2.1.9版本后, 基本上不会出现那种问题了
