### ISSUE TITLE
降低提示频率+固定位置调整

### ISSUE THREAD

**Issue by photkey** [flyinclouds/KBLAutoSwitch#9]
### 1、降低提示频率
频繁切换应用的时候，每切换一次都提示一次，稍有点烦人……
是否能够降低一下提示的频率，比方：只有在切换了输入法时（中文切到英文/英文切到中文）才提示，如果输入法没有发生切换则不提示。
### 2、固定位置调整
如果副屏的应用获取不到输入位置，会在主屏显示固定位置的提示，这个……
当获取不到输入位置的时候，是否可以获取到当前应用的位置？比方应用左上角的xy坐标，然后根据这个位置 可自定义偏移量。

**Comment by flyinclouds** [comment]
1. 第一点无法实现，切换窗口间隔着alt+tab窗口，而且窗口切换需要知道当前窗口的状态
2. 固定位置的提示代码应该是根据当前激活的窗口判断对应屏幕，但未测试，后续测试后回复

**Comment by photkey** [comment]
![image](https://user-images.githubusercontent.com/60434581/184522560-f53fb737-1fb1-4946-ae39-a9ce913c46bf.png)
是否能够增加一个“仅输入位置”的模式？如果获取不到输入位置，就不显示提示，这个可以不完美的部分解决问题1。
因为：在获取不到输入位置时，大多数情况下其实也不必提示输入法状态，因为基本也不输入文字，只要保证正确的切换了输入法即可，比方Photoshop中切换到英文 方便按快捷键，但是这个是否提示并不重要的。

特殊一点的窗口可能就是终端一类的窗口，这种特殊窗口可能用“输入+固定位置”更好一点；
所以是否可以在“高级窗口”自定义增加窗口组，这个组可以独立的设置 提示模式，这样针对不同的应用，可以 设置不同的提示模式。

**Comment by flyinclouds** [comment]
固定模式显示是你在切换窗口、切换输入法和点击输入位置时才会提示，目前暂时没有你上述的功能开发意愿，不好意思

**Comment by KnIfER** [comment]
看我的：


https://user-images.githubusercontent.com/11593903/227788264-1d557f49-cf62-4783-a274-4e94576e3f12.mp4
